#[theme]
#primaryColor = "F633364"
#backgroundColor = "grey"

#pastel mint num 1
#[theme]
#primaryColor = "#C1E1C1"            # Verde menta suave
#backgroundColor = "#F0FFF4"         # Verde pálido de fondo
#secondaryBackgroundColor = "#E4FAE4"
#textColor = "#000000"               # Texto en negro
#font = "sans serif"


#pastel blue num 2

[theme]
primaryColor = "#AECBFA"           # Azul pastel suave
backgroundColor = "#EFF6FF"        # Azul muy claro de fondo
textColor = "#1B2631"              # Gris oscuro para contraste
secondaryBackgroundColor = "#DCEEFF"

#pastel blue num 3

#[theme]
#primaryColor = "#FFD1DC"           # Rosa pastel
#backgroundColor = "#FFF5F8"        # Rosa muy claro
#textColor = "#3A1F2B"
#secondaryBackgroundColor = "#FFE4E9"


#pastel lavender num 4

#[theme]
#primaryColor = "#E6E6FA"           # Lavanda claro
#backgroundColor = "#FAFAFF"        # Blanco con matiz lavanda
#textColor = "#2D1F3E"
#secondaryBackgroundColor = "#F0F0FF"


#pastel peach num 5

#[theme]
#primaryColor = "#FFDAB9"           # Durazno/pastel melocotón
#backgroundColor = "#FFF9F2"        # Crema muy suave
#textColor = "#432F1D"
#secondaryBackgroundColor = "#FFEEDC"
